FROM debian:bullseye-slim

ENV TZ=Asia/Shanghai
WORKDIR /opt/media/bin/

RUN sed -i 's|http://deb.debian.org|http://mirrors.aliyun.com|g; \
            s|http://security.debian.org|http://mirrors.aliyun.com|g' /etc/apt/sources.list


RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    tzdata \
    libstdc++6 \
    libgcc-s1 \
    libssl1.1 \
    && rm -rf /var/lib/apt/lists/*

COPY --from=zlmediakit/zlmediakit:master /opt/media/bin /opt/media/bin
COPY --from=mwader/static-ffmpeg:6.1 /ffmpeg /usr/local/bin/ffmpeg

ADD ./build/linux_amd64/bin ./gowvp
ADD ./www ./www

RUN mkdir -p configs

RUN ln -sf /usr/local/bin/ffmpeg /usr/bin/ffmpeg && \
    chmod +x /usr/local/bin/ffmpeg

RUN ln -sf /usr/local/bin/ffmpeg /opt/media/bin/ffmpeg


LABEL Name=gowvp \
      Version=0.1.0 \
      Maintainer="xx@golang.space" \
      Description="gowvp & zlmediakit"

EXPOSE 15123 1935 8080 554 20000-20100/udp 20000-20100

CMD ["./gowvp"]
