// Code generated by godddx, DO AVOID EDIT.
package eventdb

import (
	"github.com/gowvp/gb28181/internal/core/event"
	"gorm.io/gorm"
)

var _ event.Storer = DB{}

// DB Related business namespaces
type DB struct {
	db *gorm.DB
}

// NewDB instance object
func NewDB(db *gorm.DB) DB {
	return DB{db: db}
}

// Event Get business instance
func (d DB) Event() event.EventStorer {
	return Event(d)
}

// AutoMigrate sync database
func (d DB) AutoMigrate(ok bool) DB {
	if !ok {
		return d
	}
	if err := d.db.AutoMigrate(
		new(event.Event),
	); err != nil {
		panic(err)
	}
	return d
}
