// Code generated by godddx, DO AVOID EDIT.
package eventdb

import (
	"context"

	"github.com/gowvp/owl/internal/core/event"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
)

var _ event.EventStorer = Event{}

// Event Related business namespaces
type Event DB

// NewEvent instance object
func NewEvent(db *gorm.DB) Event {
	return Event{db: db}
}

// Find implements event.EventStorer.
func (d Event) Find(ctx context.Context, bs *[]*event.Event, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return orm.FindWithContext(ctx, d.db, bs, page, opts...)
}

// Get implements event.EventStorer.
func (d Event) Get(ctx context.Context, model *event.Event, opts ...orm.QueryOption) error {
	return orm.FirstWithContext(ctx, d.db, model, opts...)
}

// Add implements event.EventStorer.
func (d Event) Add(ctx context.Context, model *event.Event) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Edit implements event.EventStorer.
func (d Event) Edit(ctx context.Context, model *event.Event, changeFn func(*event.Event), opts ...orm.QueryOption) error {
	return orm.UpdateWithContext(ctx, d.db, model, changeFn, opts...)
}

// Del implements event.EventStorer.
func (d Event) Del(ctx context.Context, model *event.Event, opts ...orm.QueryOption) error {
	return orm.DeleteWithContext(ctx, d.db, model, opts...)
}

// Count implements event.EventStorer.
func (d Event) Count(ctx context.Context, opts ...orm.QueryOption) (int64, error) {
	return orm.CountWithContext[event.Event](ctx, d.db, opts...)
}

// Session 事务组合
func (d Event) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, fn := range changeFns {
			if err := fn(tx); err != nil {
				return err
			}
		}
		return nil
	})
}

// EditWithSession 修改事务
func (d Event) EditWithSession(tx *gorm.DB, model *event.Event, changeFn func(b *event.Event) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithSession(tx, model, changeFn, opts...)
}
