// Code generated by godddx, DO AVOID EDIT.
package event

import (
	"github.com/ixugo/goddd/pkg/orm"
	"github.com/ixugo/goddd/pkg/web"
)

type FindEventInput struct {
	web.PagerFilter
	web.DateFilter
	DID   string `form:"did"`   // 设备 ID
	CID   string `form:"cid"`   // 通道 ID
	Label string `form:"label"` // 检测标签
}

type EditEventInput struct {
	EndedAt orm.Time `json:"ended_at"` // 事件结束时间 (毫秒时间戳)
}

type AddEventInput struct {
	DID       string   `json:"-"`          // 设备 ID (API 层填充)
	CID       string   `json:"-"`          // 通道 ID (API 层填充)
	StartedAt orm.Time `json:"started_at"` // 事件开始时间 (毫秒时间戳)
	EndedAt   orm.Time `json:"ended_at"`   // 事件结束时间 (毫秒时间戳)
	Label     string   `json:"label"`      // 检测标签
	Score     float32  `json:"score"`      // 置信度
	Zones     string   `json:"zones"`      // 检测区域 JSON
	ImagePath string   `json:"image_path"` // 图片相对路径
	Model     string   `json:"model"`      // 分析模型名称
}
