// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"log/slog"
	"net/http"

	"github.com/gowvp/owl/internal/conf"
	"github.com/gowvp/owl/internal/data"
	"github.com/gowvp/owl/internal/web/api"
	"github.com/gowvp/owl/pkg/gbs"
	"github.com/ixugo/goddd/domain/version/versionapi"
)

// Injectors from wire.go:

func wireApp(bc *conf.Bootstrap, log *slog.Logger) (http.Handler, func(), error) {
	db, err := data.SetupDB(bc)
	if err != nil {
		return nil, nil, err
	}
	core := versionapi.NewVersionCore(db)
	versionapiAPI := versionapi.New(core)
	smsCore := api.NewSMSCore(db, bc)
	smsAPI := api.NewSmsAPI(smsCore)
	uniqueidCore := api.NewUniqueID(db)
	storer := api.NewIPCStore(db)
	adapter := api.NewGBAdapter(storer, uniqueidCore)
	server, cleanup := gbs.NewServer(bc, adapter, smsCore)
	ipcCore := api.NewIPCCore(storer, uniqueidCore, nil) // protocols 会在下面赋值
	v := api.NewProtocols(adapter, smsCore, ipcCore, server)
	// 重新初始化 ipcCore 以包含 protocols
	ipcCore = api.NewIPCCore(storer, uniqueidCore, v)
	webHookAPI := api.NewWebHookAPI(smsCore, bc, server, ipcCore, v)
	ipcapi := api.NewIPCAPI(ipcCore)
	configAPI := api.NewConfigAPI(db, bc)
	userAPI := api.NewUserAPI(bc)
	eventCore := api.NewEventCore(db, bc)
	aiWebhookAPI := api.NewAIWebhookAPIWithDeps(bc, eventCore, ipcCore)
	eventAPI := api.NewEventAPI(eventCore, bc)
	usecase := &api.Usecase{
		Conf:         bc,
		DB:           db,
		Version:      versionapiAPI,
		SMSAPI:       smsAPI,
		WebHookAPI:   webHookAPI,
		UniqueID:     uniqueidCore,
		GB28181API:   ipcapi,
		ConfigAPI:    configAPI,
		SipServer:    server,
		UserAPI:      userAPI,
		AIWebhookAPI: aiWebhookAPI,
		EventAPI:     eventAPI,
	}
	handler := api.NewHTTPHandler(usecase)
	return handler, func() {
		cleanup()
	}, nil
}
