// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"log/slog"
	"net/http"

	"github.com/gowvp/gb28181/internal/conf"
	"github.com/gowvp/gb28181/internal/data"
	"github.com/gowvp/gb28181/internal/web/api"
	"github.com/gowvp/gb28181/pkg/gbs"
	"github.com/ixugo/goddd/domain/version/versionapi"
)

// Injectors from wire.go:

func wireApp(bc *conf.Bootstrap, log *slog.Logger) (http.Handler, func(), error) {
	db, err := data.SetupDB(bc)
	if err != nil {
		return nil, nil, err
	}
	core := versionapi.NewVersionCore(db)
	versionapiAPI := versionapi.New(core)
	smsCore := api.NewSMSCore(db, bc)
	smsAPI := api.NewSmsAPI(smsCore)
	uniqueidCore := api.NewUniqueID(db)
	pushCore := api.NewPushCore(db, uniqueidCore)
	storer := api.NewIPCStore(db)
	adapter := api.NewGBAdapter(storer, uniqueidCore)
	server, cleanup := gbs.NewServer(bc, adapter, smsCore)
	proxyCore := api.NewProxyCore(db, uniqueidCore)
	v := api.NewProtocols(adapter, smsCore, proxyCore, server)
	ipcCore := api.NewIPCCore(storer, uniqueidCore, v)
	webHookAPI := api.NewWebHookAPI(smsCore, pushCore, bc, server, ipcCore, v)
	pushAPI := api.NewPushAPI(pushCore, smsCore, bc)
	ipcapi := api.NewIPCAPI(ipcCore)
	proxyAPI := api.NewProxyAPI(proxyCore)
	configAPI := api.NewConfigAPI(db, bc)
	userAPI := api.NewUserAPI(bc)
	aiWebhookAPI := api.NewAIWebhookAPI(bc)
	usecase := &api.Usecase{
		Conf:         bc,
		DB:           db,
		Version:      versionapiAPI,
		SMSAPI:       smsAPI,
		WebHookAPI:   webHookAPI,
		UniqueID:     uniqueidCore,
		MediaAPI:     pushAPI,
		GB28181API:   ipcapi,
		ProxyAPI:     proxyAPI,
		ConfigAPI:    configAPI,
		SipServer:    server,
		UserAPI:      userAPI,
		AIWebhookAPI: aiWebhookAPI,
	}
	handler := api.NewHTTPHandler(usecase)
	return handler, func() {
		cleanup()
	}, nil
}
