// Code generated by godddx, DO AVOID EDIT.
package ipcdb

import (
	"context"

	"github.com/gowvp/gb28181/internal/core/ipc"
	"github.com/ixugo/goddd/pkg/orm"
	"gorm.io/gorm"
)

var _ ipc.ChannelStorer = Channel{}

// Channel Related business namespaces
type Channel DB

// BatchEdit implements ipc.ChannelStorer.
func (d Channel) BatchEdit(ctx context.Context, column string, value any, args ...orm.QueryOption) error {
	if len(args) == 0 {
		panic("没有查询条件")
	}
	db := d.db.WithContext(ctx).Model(new(ipc.Channel))
	for _, fn := range args {
		fn(db)
	}
	return db.UpdateColumn(column, value).Error
}

// NewChannel instance object
func NewChannel(db *gorm.DB) Channel {
	return Channel{db: db}
}

// Find implements ipc.ChannelStorer.
func (d Channel) Find(ctx context.Context, bs *[]*ipc.Channel, page orm.Pager, opts ...orm.QueryOption) (int64, error) {
	return orm.FindWithContext(ctx, d.db, bs, page, opts...)
}

// Get implements ipc.ChannelStorer.
func (d Channel) Get(ctx context.Context, model *ipc.Channel, opts ...orm.QueryOption) error {
	return orm.FirstWithContext(ctx, d.db, model, opts...)
}

// Add implements ipc.ChannelStorer.
func (d Channel) Add(ctx context.Context, model *ipc.Channel) error {
	return d.db.WithContext(ctx).Create(model).Error
}

// Edit implements ipc.ChannelStorer.
func (d Channel) Edit(ctx context.Context, model *ipc.Channel, changeFn func(*ipc.Channel) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithContext2(ctx, d.db, model, changeFn, opts...)
}

// Del implements ipc.ChannelStorer.
func (d Channel) Del(ctx context.Context, model *ipc.Channel, opts ...orm.QueryOption) error {
	return orm.DeleteWithContext(ctx, d.db, model, opts...)
}

func (d Channel) Session(ctx context.Context, changeFns ...func(*gorm.DB) error) error {
	return d.db.WithContext(ctx).Transaction(func(tx *gorm.DB) error {
		for _, fn := range changeFns {
			if err := fn(tx); err != nil {
				return err
			}
		}
		return nil
	})
}

func (d Channel) EditWithSession(tx *gorm.DB, model *ipc.Channel, changeFn func(b *ipc.Channel) error, opts ...orm.QueryOption) error {
	return orm.UpdateWithSession(tx, model, changeFn, opts...)
}
