// Code generated by godddx, DO AVOID EDIT.
package ipcdb

import (
	"github.com/gowvp/owl/internal/core/ipc"
	"gorm.io/gorm"
)

var _ ipc.Storer = DB{}

// DB Related business namespaces
type DB struct {
	db *gorm.DB
}

// NewDB instance object
func NewDB(db *gorm.DB) DB {
	return DB{db: db}
}

// Device Get business instance
func (d DB) Device() ipc.DeviceStorer {
	return Device(d)
}

// Channel Get business instance
func (d DB) Channel() ipc.ChannelStorer {
	return Channel(d)
}

// AutoMigrate sync database
func (d DB) AutoMigrate(ok bool) DB {
	if !ok {
		return d
	}
	if err := d.db.AutoMigrate(
		new(ipc.Device),
		new(ipc.Channel),
	); err != nil {
		panic(err)
	}
	return d
}
