// Code generated by godddx, DO AVOID EDIT.
package eventcache

import (
	"github.com/gowvp/gb28181/internal/core/event"
	"github.com/ixugo/goddd/pkg/conc"
)

var _ event.Storer = (*Cache)(nil)

func NewCache(store event.Storer, cache conc.Cacher) *Cache {
	return &Cache{
		store: store,
		event: cache,
	}
}

type Cache struct {
	store event.Storer
	event conc.Cacher
}

// Event implements event.EventStorer
func (c *Cache) Event() event.EventStorer {
	return (*Event)(c)
}
