// Code generated by godddx, DO AVOID EDIT.
package recordingdb

import (
	"github.com/gowvp/owl/internal/core/recording"
	"gorm.io/gorm"
)

var _ recording.Storer = DB{}

// DB Related business namespaces
type DB struct {
	db *gorm.DB
}

// NewDB instance object
func NewDB(db *gorm.DB) DB {
	return DB{db: db}
}

// Recording Get business instance
func (d DB) Recording() recording.RecordingStorer {
	return Recording(d)
}

// AutoMigrate sync database
func (d DB) AutoMigrate(ok bool) DB {
	if !ok {
		return d
	}
	if err := d.db.AutoMigrate(
		new(recording.Recording),
	); err != nil {
		panic(err)
	}
	return d
}
