// Code generated by godddx, DO AVOID EDIT.
package ipc

import "github.com/ixugo/goddd/pkg/web"

type FindChannelInput struct {
	web.PagerFilter
	DID      string `form:"did"`       // 设备 id
	DeviceID string `form:"device_id"` // 国标编码
	Key      string `form:"key"`       // 名称/国标编码 模糊搜索，id 精确搜索
	IsOnline string `form:"is_online"` // 是否在线
	Type     string `form:"type"`      // 通道类型 (GB28181/ONVIF/RTMP/RTSP)
	App      string `form:"app"`       // 应用名
	Stream   string `form:"stream"`    // 流 ID
}

type EditChannelInput struct {
	DeviceID string    `json:"device_id"` // 国标编码
	Name     string    `json:"name"`      // 通道名称
	PTZType  int       `json:"ptztype"`   // 云台类型
	IsOnline bool      `json:"is_online"` // 是否在线
	Ext      DeviceExt `json:"ext"`

	// RTMP/RTSP 配置
	// App    string       `json:"app"`    // 应用名
	// Stream string       `json:"stream"` // 流 ID
	Config StreamConfig `json:"config"` // 流配置
}

// AddChannelInput 添加通道请求参数，支持 RTMP/RTSP 类型
type AddChannelInput struct {
	Type       string `json:"type"`        // 通道类型 (RTMP/RTSP)
	Name       string `json:"name"`        // 通道名称
	DeviceID   string `json:"device_id"`   // 可选，关联的父设备 ID
	DeviceName string `json:"device_name"` // 可选，device_id 不存在时用于创建新设备

	// RTMP/RTSP 配置
	App    string       `json:"app"`    // 应用名
	Stream string       `json:"stream"` // 流 ID
	Config StreamConfig `json:"config"` // 流配置
}

type AddZoneInput struct {
	Name        string    `json:"name"`        // 区域名称
	Coordinates []float32 `json:"coordinates"` // 坐标
	Color       string    `json:"color"`       // 颜色，支持 hex 颜色值，如 #FF0000
	Labels      []string  `json:"labels"`      // 标签
	ChannelID   string    `json:"-"`           // 通道 id
}
