// Code generated by godddx, DO AVOID EDIT.
package ipc

import (
	"github.com/ixugo/goddd/domain/uniqueid"
)

// Storer data persistence
type Storer interface {
	Device() DeviceStorer
	Channel() ChannelStorer
}

// Core business domain
type Core struct {
	store     Storer
	uniqueID  uniqueid.Core
	protocols map[string]Protocoler // 协议映射（Protocol 在同一个包内）
}

// NewCore create business domain
func NewCore(store Storer, uni uniqueid.Core, protocols map[string]Protocoler) Core {
	return Core{
		store:     store,
		uniqueID:  uni,
		protocols: protocols,
	}
}

func (c *Core) GetProtocol(atype string) Protocoler {
	return c.protocols[atype]
}

// SetProtocols 设置协议映射，用于解决循环依赖问题
func (c *Core) SetProtocols(protocols map[string]Protocoler) {
	c.protocols = protocols
}
