// Code generated by godddx, DO AVOID EDIT.
package recordingcache

import (
	"github.com/gowvp/owl/internal/core/recording"
	"github.com/ixugo/goddd/pkg/conc"
)

var _ recording.Storer = (*Cache)(nil)

func NewCache(store recording.Storer, cache conc.Cacher) *Cache {
	return &Cache{
		store:     store,
		recording: cache,
	}
}

type Cache struct {
	store     recording.Storer
	recording conc.Cacher
}

// Recording implements recording.RecordingStorer
func (c *Cache) Recording() recording.RecordingStorer {
	return (*Recording)(c)
}
